[package]
name = "assets_embedded"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assets_manager = { version = "0.7.2", features = ["embedded"] }
once_cell = "1.9.0"
